spring:
  mvc:
    servlet:
      load-on-startup: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
logging:
  level:
    root: info
    com.xshhope: debug
  file: logs/${spring.application.name}.log
zuul:
  ignored-services: '*'
  sensitiveHeaders:
  routes:
    oauth:
      path: /api-o/**
      serviceId: oauth-center
    api-u:
      path: /api-u/**
      serviceId: user-center
    apply:
      path: /api-a/**
      serviceId: user-apply
    log:
      path: /api-l/**
      serviceId: log-center
    pay:
      path: /api-p/**
      serviceId: pay-center
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  add-proxy-headers: true
  ribbon:
    eager-load:
      enabled: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
cron:
  black-ip: 0 0/5 * * * ?